/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ustunerturizm2;

import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author iserh
 */
public class frmGirisEkrani extends javax.swing.JFrame {

    /**
     * Creates new form frmGirisEkrani
     *
     */
    public frmGirisEkrani() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMusteriEkle = new javax.swing.JButton();
        btnMusteriGoruntule = new javax.swing.JButton();
        btnOtobusEkle = new javax.swing.JButton();
        btnKayitliOtobusler = new javax.swing.JButton();
        btnTurOlustur = new javax.swing.JButton();
        btnKayitliTurlar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Üstüner Turzim Müşteri Takip ");
        setResizable(false);

        btnMusteriEkle.setText("Müşteri Ekle");
        btnMusteriEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusteriEkleActionPerformed(evt);
            }
        });

        btnMusteriGoruntule.setText("Kayıtlı Müşteriler");
        btnMusteriGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusteriGoruntuleActionPerformed(evt);
            }
        });

        btnOtobusEkle.setText("Otobüs Ekle");
        btnOtobusEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtobusEkleActionPerformed(evt);
            }
        });

        btnKayitliOtobusler.setText("Kayıtlı Otobüsler");
        btnKayitliOtobusler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayitliOtobuslerActionPerformed(evt);
            }
        });

        btnTurOlustur.setText("Tur Oluştur");
        btnTurOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurOlusturActionPerformed(evt);
            }
        });

        btnKayitliTurlar.setText("Kayıtlı Turlar");
        btnKayitliTurlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayitliTurlarActionPerformed(evt);
            }
        });

        jButton1.setText("Verileri Yedekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Yedekten Yükle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTurOlustur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMusteriEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(btnOtobusEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKayitliTurlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMusteriGoruntule, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnKayitliOtobusler, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTurOlustur)
                    .addComponent(btnKayitliTurlar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMusteriEkle)
                    .addComponent(btnMusteriGoruntule))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOtobusEkle)
                    .addComponent(btnKayitliOtobusler))
                .addGap(49, 49, 49)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Müşteri Görüntüleme Ekranı");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private frmMusteriGoruntule f2 = new frmMusteriGoruntule();
    private frmMusteriEkle f1 = new frmMusteriEkle();
    private frmOtobusEkle f3 = new frmOtobusEkle();
    private frmOtobusGoruntule f4 = new frmOtobusGoruntule();
    private frmTurOlustur F5 = new frmTurOlustur();
    private frmTurGoruntule F6 = new frmTurGoruntule();
    

    private void btnMusteriEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusteriEkleActionPerformed
        // TODO add your handling code here:
        getF1().setMusteri(getF2());
        getF1().setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        getF1().setVisible(true);
        
    }//GEN-LAST:event_btnMusteriEkleActionPerformed

    private void btnMusteriGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusteriGoruntuleActionPerformed
        // TODO add your handling code here:
        getF2().populateTable();
        getF2().setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        getF2().setVisible(true);
    }//GEN-LAST:event_btnMusteriGoruntuleActionPerformed

    private void btnOtobusEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtobusEkleActionPerformed
        // TODO add your handling code here:
        getF3().setFrmOtobus(getF4());
        getF3().setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        getF3().setVisible(true);
    }//GEN-LAST:event_btnOtobusEkleActionPerformed

    private void btnKayitliOtobuslerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayitliOtobuslerActionPerformed
        // TODO add your handling code here:

        getF4().setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        getF4().setVisible(true);
    }//GEN-LAST:event_btnKayitliOtobuslerActionPerformed

    private void btnTurOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurOlusturActionPerformed
        // TODO add your handling code here:
        getF5().populateTable();
        getF5().setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        getF5().setVisible(true);

    }//GEN-LAST:event_btnTurOlusturActionPerformed

    private void btnKayitliTurlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayitliTurlarActionPerformed
        // TODO add your handling code here:
        getF6().populateTable();
        getF6().setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        getF6().setVisible(true);
    }//GEN-LAST:event_btnKayitliTurlarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            mySQLBackupRestore.Backupdbtosql();
        } catch (IOException ex) {
            Logger.getLogger(frmGirisEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            mySQLBackupRestore.Backupdbtosql();
        } catch (IOException ex) {
            Logger.getLogger(frmGirisEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            frmGirisEkrani fgiris = new frmGirisEkrani();
            fgiris.setVisible(true);

        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKayitliOtobusler;
    private javax.swing.JButton btnKayitliTurlar;
    private javax.swing.JButton btnMusteriEkle;
    private javax.swing.JButton btnMusteriGoruntule;
    private javax.swing.JButton btnOtobusEkle;
    private javax.swing.JButton btnTurOlustur;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the f2
     */
    public frmMusteriGoruntule getF2() {
        return f2;
    }

    /**
     * @param f2 the f2 to set
     */
    public void setF2(frmMusteriGoruntule f2) {
        this.f2 = f2;
    }

    /**
     * @return the f1
     */
    public frmMusteriEkle getF1() {
        return f1;
    }

    /**
     * @param f1 the f1 to set
     */
    public void setF1(frmMusteriEkle f1) {
        this.f1 = f1;
    }

    /**
     * @return the f3
     */
    public frmOtobusEkle getF3() {
        return f3;
    }

    /**
     * @param f3 the f3 to set
     */
    public void setF3(frmOtobusEkle f3) {
        this.f3 = f3;
    }

    /**
     * @return the f4
     */
    public frmOtobusGoruntule getF4() {
        return f4;
    }

    /**
     * @param f4 the f4 to set
     */
    public void setF4(frmOtobusGoruntule f4) {
        this.f4 = f4;
    }

    /**
     * @return the F5
     */
    public frmTurOlustur getF5() {
        return F5;
    }

    /**
     * @param F5 the F5 to set
     */
    public void setF5(frmTurOlustur F5) {
        this.F5 = F5;
    }

    /**
     * @return the F6
     */
    public frmTurGoruntule getF6() {
        return F6;
    }

    /**
     * @param F6 the F6 to set
     */
    public void setF6(frmTurGoruntule F6) {
        this.F6 = F6;
    }
}
