/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ustunerturizm2;

import java.awt.Toolkit;
import java.util.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author iserh
 */
public final class frmMusteriGoruntule extends javax.swing.JFrame {

    DefaultListModel model = new DefaultListModel();
    DefaultTableModel dfmodel = new DefaultTableModel();

    /**
     * Creates new form frmMusteriGoruntule
     */
    public frmMusteriGoruntule() {
        initComponents();
        setLocationRelativeTo(null);
        populateTable();
        tblMusteriler.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        getRootPane().setDefaultButton(btnKaydet);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmMusteriGorDuzenle = new javax.swing.JFrame();
        txtAd = new javax.swing.JTextField();
        txtSoyad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTCKN = new javax.swing.JTextField();
        txtTelNo = new javax.swing.JTextField();
        txtHESKod = new javax.swing.JTextField();
        txtGecmisTurlar = new javax.swing.JTextField();
        txtIstenenTurlar = new javax.swing.JTextField();
        txtYorum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnKaydet = new javax.swing.JButton();
        optCancelContinue = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMusteriler = new javax.swing.JTable();
        btnGoruntule = new javax.swing.JButton();
        txtAramaAd = new javax.swing.JTextField();
        txtAramaSoyad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAra = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();

        frmMusteriGorDuzenle.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frmMusteriGorDuzenle.setTitle("Müşteri Görüntüle/Düzenle");
        frmMusteriGorDuzenle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        frmMusteriGorDuzenle.setMinimumSize(new java.awt.Dimension(422, 510));
        frmMusteriGorDuzenle.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                frmMusteriGorDuzenleWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                frmMusteriGorDuzenleWindowClosing(evt);
            }
        });

        txtAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdActionPerformed(evt);
            }
        });
        txtAd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdKeyReleased(evt);
            }
        });

        txtSoyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoyadActionPerformed(evt);
            }
        });
        txtSoyad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoyadKeyReleased(evt);
            }
        });

        jLabel4.setText("Ad");

        jLabel5.setText("Soyad");

        txtTCKN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTCKNActionPerformed(evt);
            }
        });
        txtTCKN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTCKNKeyReleased(evt);
            }
        });

        txtTelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelNoActionPerformed(evt);
            }
        });
        txtTelNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelNoKeyReleased(evt);
            }
        });

        txtHESKod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHESKodKeyReleased(evt);
            }
        });

        txtGecmisTurlar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGecmisTurlarKeyReleased(evt);
            }
        });

        txtIstenenTurlar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIstenenTurlarKeyReleased(evt);
            }
        });

        txtYorum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtYorumKeyReleased(evt);
            }
        });

        jLabel6.setText("TC Kimlik Numarası");

        jLabel7.setText("Telefon Numarası");

        jLabel8.setText("HES Kodu");

        jLabel9.setText("Katıldığı Turlar");

        jLabel10.setText("Katılmak İstediği Turlar");

        jLabel11.setText("Müşteri Hakkında Yorum");

        btnKaydet.setText("Kaydet");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmMusteriGorDuzenleLayout = new javax.swing.GroupLayout(frmMusteriGorDuzenle.getContentPane());
        frmMusteriGorDuzenle.getContentPane().setLayout(frmMusteriGorDuzenleLayout);
        frmMusteriGorDuzenleLayout.setHorizontalGroup(
            frmMusteriGorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmMusteriGorDuzenleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmMusteriGorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmMusteriGorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10))
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmMusteriGorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtYorum, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frmMusteriGorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtSoyad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(txtAd, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHESKod, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtIstenenTurlar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTCKN, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTelNo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtGecmisTurlar, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frmMusteriGorDuzenleLayout.setVerticalGroup(
            frmMusteriGorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmMusteriGorDuzenleLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(frmMusteriGorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmMusteriGorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmMusteriGorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTCKN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmMusteriGorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmMusteriGorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHESKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmMusteriGorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGecmisTurlar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmMusteriGorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIstenenTurlar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmMusteriGorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYorum, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(27, 27, 27)
                .addComponent(btnKaydet)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout optCancelContinueLayout = new javax.swing.GroupLayout(optCancelContinue.getContentPane());
        optCancelContinue.getContentPane().setLayout(optCancelContinueLayout);
        optCancelContinueLayout.setHorizontalGroup(
            optCancelContinueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        optCancelContinueLayout.setVerticalGroup(
            optCancelContinueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Müşteri Görüntüleme Ekranı");
        setResizable(false);

        tblMusteriler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ad", "Soyad", "TC Kimlik No", "Tel No"
            }
        ));
        tblMusteriler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMusterilerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMusteriler);

        btnGoruntule.setText("Görüntüle");
        btnGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoruntuleActionPerformed(evt);
            }
        });

        txtAramaAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAramaAdActionPerformed(evt);
            }
        });

        jLabel1.setText("Ad");

        jLabel2.setText("Soyad");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Arama");

        btnAra.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAra.setText("Ara");
        btnAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAraActionPerformed(evt);
            }
        });

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGoruntule, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAramaAd)
                                .addComponent(txtAramaSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnAra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAramaAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAramaSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSil)
                    .addComponent(btnGoruntule))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAramaAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAramaAdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAramaAdActionPerformed

    private void btnAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAraActionPerformed
        // TODO add your handling code here:
        List<RowFilter<Object, Object>> filters = new ArrayList<>(2);
        filters.add(RowFilter.regexFilter(txtAramaAd.getText(), 1));
        filters.add(RowFilter.regexFilter(txtAramaSoyad.getText(), 2));
        TableRowSorter tableRowSorter = new TableRowSorter<>(dfmodel);
        tblMusteriler.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.andFilter(filters));
    }//GEN-LAST:event_btnAraActionPerformed
    public ArrayList<Musteri> getGoruntulenenMusteri() throws SQLException {
        int id = (Integer) tblMusteriler.getModel().getValueAt(tblMusteriler.convertRowIndexToModel(selectedRow), 0);
        Connection connection = null;
        DbHelper helper = new DbHelper();
        Statement statement = null;
        ResultSet resultSet;
        ArrayList<Musteri> GoruntulenenMusteri = null;
        try {
            connection = helper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("Select * from musteri WHERE ID=" + id);
            GoruntulenenMusteri = new ArrayList<>();
            while (resultSet.next()) {
                GoruntulenenMusteri.add(new Musteri(resultSet.getInt("ID"),
                        resultSet.getString("Ad"),
                        resultSet.getString("Soyad"),
                        resultSet.getString("TCKN"),
                        resultSet.getString("HESKod"),
                        resultSet.getString("TelNo"),
                        resultSet.getString("GecmisTurlar"),
                        resultSet.getString("IstenenTurlar"),
                        resultSet.getString("Yorum")));

            }
        } catch (SQLException e) {
            helper.showErrorMessage(e);

        } finally {
            statement.close();
            connection.close();
        }
        return GoruntulenenMusteri;
    }
    public int selectedRow;
    private void btnGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoruntuleActionPerformed
        try {
            selectedRow = tblMusteriler.getSelectedRow();
            ArrayList<Musteri> GoruntulenenMusteri = getGoruntulenenMusteri();
            GoruntulenenMusteri.stream().map((musteri) -> {
                txtAd.setText(musteri.getIsim());
                return musteri;
            }).map((musteri) -> {
                txtSoyad.setText(musteri.getSoyisim());
                return musteri;
            }).map((musteri) -> {
                txtTCKN.setText(musteri.getTckimlikno());
                return musteri;
            }).map((musteri) -> {
                txtTelNo.setText(musteri.getTelefonnumarasi());
                return musteri;
            }).map((musteri) -> {
                txtHESKod.setText(musteri.getHeskodu());
                return musteri;
            }).map((musteri) -> {
                txtGecmisTurlar.setText(musteri.getGecmisturlar());
                return musteri;
            }).map((musteri) -> {
                txtIstenenTurlar.setText(musteri.getIstenenturlar());
                return musteri;
            }).forEachOrdered((musteri) -> {
                txtYorum.setText(musteri.getYorum());
            });
            populateTable();

        } catch (SQLException ex) {
            Logger.getLogger(frmMusteriGoruntule.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmMusteriGorDuzenle.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        frmMusteriGorDuzenle.setLocationRelativeTo(null);
        frmMusteriGorDuzenle.setVisible(true);


    }//GEN-LAST:event_btnGoruntuleActionPerformed

    private void txtAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdActionPerformed

    private void txtSoyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoyadActionPerformed

    private void txtTCKNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTCKNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTCKNActionPerformed

    private void txtTelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelNoActionPerformed

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        // TODO add your handling code here:
        Connection connection = null;
        DbHelper helper = new DbHelper();
        PreparedStatement statement = null;
        int id = 0;
        if (txtTCKN.getText().length() != 11
                || (Integer.valueOf(txtTCKN.getText().charAt(txtTCKN.getText().length() - 1)) - 48) % 2 != 0
                || txtTCKN.getText().charAt(0) == '0'
                || ((((Integer.valueOf(txtTCKN.getText().charAt(0)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(1)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(2)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(3)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(4)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(5)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(6)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(7)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(8)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(9))) - 48) % 10)) - ((Integer.valueOf(txtTCKN.getText().charAt(10))) - 48) != 0
                || (txtTCKN.getText().charAt(0) == txtTCKN.getText().charAt(1)
                && txtTCKN.getText().charAt(1) == txtTCKN.getText().charAt(2)
                && txtTCKN.getText().charAt(2) == txtTCKN.getText().charAt(3)
                && txtTCKN.getText().charAt(3) == txtTCKN.getText().charAt(4)
                && txtTCKN.getText().charAt(4) == txtTCKN.getText().charAt(5)
                && txtTCKN.getText().charAt(5) == txtTCKN.getText().charAt(6)
                && txtTCKN.getText().charAt(6) == txtTCKN.getText().charAt(7)
                && txtTCKN.getText().charAt(7) == txtTCKN.getText().charAt(8)
                && txtTCKN.getText().charAt(8) == txtTCKN.getText().charAt(9)
                && txtTCKN.getText().charAt(10) == '0')) {
            //tckn kısa veya tek sayıyla bitiyorsa
            //tckn hatalı mesajı göster
            JOptionPane.showMessageDialog(null, "TCKN Eksik veya Hatalı", "TCKN Hatalı", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                connection = helper.getConnection();
                ArrayList<Musteri> GoruntulenenMusteri = getGoruntulenenMusteri();
                for (Musteri musteri : GoruntulenenMusteri) {
                    id = musteri.getId();
                }
                String sql = "UPDATE musteri SET Ad=?,Soyad=?,TCKN=?,TelNo=?,HESKod=?,GecmisTurlar=?,IstenenTurlar=?,Yorum=?  WHERE ID=" + id;
                statement = connection.prepareStatement(sql);
                statement.setString(1, txtAd.getText());
                statement.setString(2, txtSoyad.getText());
                statement.setString(3, txtTCKN.getText());
                statement.setString(4, txtTelNo.getText());
                statement.setString(5, txtHESKod.getText());
                statement.setString(6, txtGecmisTurlar.getText());
                statement.setString(7, txtIstenenTurlar.getText());
                statement.setString(8, txtYorum.getText());
                statement.executeUpdate();
                JOptionPane.showMessageDialog(null, "Değişiklikler Kaydedildi", "Kayıt Başarılı", JOptionPane.INFORMATION_MESSAGE);
                populateTable();

            } catch (SQLException e) {
                helper.showErrorMessage(e);
            } finally {
                try {
                    statement.close();
                    connection.close();
                } catch (SQLException ex) {
                    Logger.getLogger(frmMusteriEkle.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        // TODO add your handling code here:
        int id = (Integer) tblMusteriler.getModel().getValueAt(tblMusteriler.convertRowIndexToModel(selectedRow), 0);
        Connection connection = null;
        DbHelper helper = new DbHelper();
        PreparedStatement statement = null;
        Object[] options = {"Sil", "İptal et"};
        int n = JOptionPane.showOptionDialog(optCancelContinue,
                "Bu müşteriyi silmek istediğinize emin misiniz?",
                "Emin misiniz?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        switch (n) {
            case JOptionPane.YES_OPTION:
                try {
                connection = helper.getConnection();
                String sql = "DELETE from musteri WHERE ID=" + id;
                statement = connection.prepareStatement(sql);
                statement.executeUpdate();
                JOptionPane.showMessageDialog(null, "Müşteri silindi", "İşlem Başarılı", JOptionPane.INFORMATION_MESSAGE);
                populateTable();

            } catch (SQLException ex) {
                Logger.getLogger(frmMusteriGoruntule.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    statement.close();
                    connection.close();
                } catch (SQLException ex) {
                    Logger.getLogger(frmMusteriEkle.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                break;
        }


    }//GEN-LAST:event_btnSilActionPerformed

    private void frmMusteriGorDuzenleWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frmMusteriGorDuzenleWindowClosed
//        // TODO add your handling code here:

        frmMusteriGorDuzenle.setVisible(false);
    }//GEN-LAST:event_frmMusteriGorDuzenleWindowClosed

    private void frmMusteriGorDuzenleWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frmMusteriGorDuzenleWindowClosing
        // TODO add your handling code here:
        frmMusteriGorDuzenle.setVisible(false);
    }//GEN-LAST:event_frmMusteriGorDuzenleWindowClosing

    private void tblMusterilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMusterilerMouseClicked
        // TODO add your handling code here:
        selectedRow = tblMusteriler.getSelectedRow();
    }//GEN-LAST:event_tblMusterilerMouseClicked

    private void txtTCKNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTCKNKeyReleased
        // TODO add your handling code here:
        try {
            Integer.parseInt(txtTCKN.getText());

        } catch (NumberFormatException e) {
            txtTCKN.setText(txtTCKN.getText().replaceAll("[^0-9]", ""));
        }
    }//GEN-LAST:event_txtTCKNKeyReleased

    private void txtTelNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelNoKeyReleased
        // TODO add your handling code here:
        try {
            Integer.parseInt(txtTelNo.getText());

        } catch (NumberFormatException e) {
            txtTelNo.setText(txtTelNo.getText().replaceAll("[^0-9]", ""));
        }
    }//GEN-LAST:event_txtTelNoKeyReleased

    private void txtHESKodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHESKodKeyReleased
        // TODO add your handling code here:
        txtHESKod.setText(txtHESKod.getText().replaceAll("^\\s+", ""));
    }//GEN-LAST:event_txtHESKodKeyReleased

    private void txtGecmisTurlarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGecmisTurlarKeyReleased
        // TODO add your handling code here:
        txtGecmisTurlar.setText(txtGecmisTurlar.getText().replaceAll("^\\s+", ""));
    }//GEN-LAST:event_txtGecmisTurlarKeyReleased

    private void txtIstenenTurlarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIstenenTurlarKeyReleased
        // TODO add your handling code here:
        txtIstenenTurlar.setText(txtIstenenTurlar.getText().replaceAll("^\\s+", ""));
    }//GEN-LAST:event_txtIstenenTurlarKeyReleased

    private void txtYorumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYorumKeyReleased
        // TODO add your handling code here:
        txtYorum.setText(txtYorum.getText().replaceAll("^\\s+", ""));
    }//GEN-LAST:event_txtYorumKeyReleased

    private void txtAdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdKeyReleased
        // TODO add your handling code here:
        txtAd.setText(txtAd.getText().replaceAll("^\\s+", ""));
    }//GEN-LAST:event_txtAdKeyReleased

    private void txtSoyadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoyadKeyReleased
        // TODO add your handling code here:
        txtSoyad.setText(txtSoyad.getText().replaceAll("^\\s+", ""));
    }//GEN-LAST:event_txtSoyadKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMusteriGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMusteriGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMusteriGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMusteriGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmMusteriGoruntule().setVisible(true);
        });
    }

    public ArrayList<Musteri> getMusteri() throws SQLException {
        Connection connection = null;
        DbHelper helper = new DbHelper();
        Statement statement = null;
        ResultSet resultSet;
        ArrayList<Musteri> musteriler = null;
        try {
            connection = helper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("Select * from musteri");
            musteriler = new ArrayList<>();
            while (resultSet.next()) {
                musteriler.add(new Musteri(resultSet.getInt("ID"),
                        resultSet.getString("Ad"),
                        resultSet.getString("Soyad"),
                        resultSet.getString("TCKN"),
                        resultSet.getString("TelNo"),
                        resultSet.getString("HESKod"),
                        resultSet.getString("GecmisTurlar"),
                        resultSet.getString("IstenenTurlar"),
                        resultSet.getString("Yorum")));

            }
        } catch (SQLException e) {
            helper.showErrorMessage(e);

        } finally {
            statement.close();
            connection.close();
        }
        return musteriler;

    }

    public void populateTable() {
        dfmodel.setRowCount(0);
        dfmodel = (DefaultTableModel) tblMusteriler.getModel();
        try {
            ArrayList<Musteri> musteriler = getMusteri();
            for (Musteri musteri : musteriler) {
                Object[] row = {
                    musteri.getId(),
                    musteri.getIsim(),
                    musteri.getSoyisim(),
                    musteri.getTckimlikno(),
                    musteri.getHeskodu()};
                dfmodel.addRow(row);

            }
            if (tblMusteriler.getColumnName(0).equals("ID")) {
                tblMusteriler.removeColumn(tblMusteriler.getColumn("ID"));
            }
        } catch (SQLException ex) {
            DbHelper help = new DbHelper();
            help.showErrorMessage(ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAra;
    private javax.swing.JButton btnGoruntule;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnSil;
    private javax.swing.JFrame frmMusteriGorDuzenle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog optCancelContinue;
    private javax.swing.JTable tblMusteriler;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtAramaAd;
    private javax.swing.JTextField txtAramaSoyad;
    private javax.swing.JTextField txtGecmisTurlar;
    private javax.swing.JTextField txtHESKod;
    private javax.swing.JTextField txtIstenenTurlar;
    private javax.swing.JTextField txtSoyad;
    private javax.swing.JTextField txtTCKN;
    private javax.swing.JTextField txtTelNo;
    private javax.swing.JTextField txtYorum;
    // End of variables declaration//GEN-END:variables
}
