/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ustunerturizm2;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author iserh
 */
public class frmMusteriEkle extends javax.swing.JFrame {

    /**
     * Creates new form frmMusteriEkle
     */
    public frmMusteriEkle() {

        initComponents();
        add(btnEkle);
        getRootPane().setDefaultButton(btnEkle);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eklemeBasarili = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        optCancelContinue = new javax.swing.JOptionPane();
        optPaneUyari = new javax.swing.JOptionPane();
        txtAd = new javax.swing.JTextField();
        txtSoyad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTCKN = new javax.swing.JTextField();
        txtTelNo = new javax.swing.JTextField();
        txtHESKod = new javax.swing.JTextField();
        txtGecmisTurlar = new javax.swing.JTextField();
        txtIstenenTurlar = new javax.swing.JTextField();
        txtYorum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnEkle = new javax.swing.JButton();

        eklemeBasarili.setMinimumSize(new java.awt.Dimension(270, 129));
        setLocationRelativeTo(null);

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Müşteri Eklendi");

        javax.swing.GroupLayout eklemeBasariliLayout = new javax.swing.GroupLayout(eklemeBasarili.getContentPane());
        eklemeBasarili.getContentPane().setLayout(eklemeBasariliLayout);
        eklemeBasariliLayout.setHorizontalGroup(
            eklemeBasariliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eklemeBasariliLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(115, 115, 115))
            .addGroup(eklemeBasariliLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eklemeBasariliLayout.setVerticalGroup(
            eklemeBasariliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eklemeBasariliLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(41, 41, 41))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Müşteri Ekleme Ekranı");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        txtAd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdKeyReleased(evt);
            }
        });

        txtSoyad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoyadKeyReleased(evt);
            }
        });

        jLabel2.setText("Ad");

        jLabel3.setText("Soyad");

        txtTCKN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTCKNKeyReleased(evt);
            }
        });

        txtTelNo.setText(" ");
        txtTelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelNoActionPerformed(evt);
            }
        });
        txtTelNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelNoKeyReleased(evt);
            }
        });

        txtHESKod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHESKodKeyReleased(evt);
            }
        });

        txtGecmisTurlar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGecmisTurlarKeyReleased(evt);
            }
        });

        txtIstenenTurlar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIstenenTurlarKeyReleased(evt);
            }
        });

        txtYorum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtYorumKeyReleased(evt);
            }
        });

        jLabel4.setText("TC Kimlik Numarası");

        jLabel5.setText("Telefon Numarası");

        jLabel6.setText("HES Kodu");

        jLabel7.setText("Katıldığı Turlar");

        jLabel8.setText("Katılmak İstediği Turlar");

        jLabel9.setText("Müşteri Hakkında Yorum");

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8))
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtYorum, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtSoyad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(txtAd, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHESKod, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtIstenenTurlar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTCKN, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTelNo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtGecmisTurlar, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTCKN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHESKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGecmisTurlar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIstenenTurlar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYorum, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27)
                .addComponent(btnEkle)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private frmMusteriGoruntule frmMusteri = new frmMusteriGoruntule();

    public frmMusteriGoruntule getFrmMusteri() {
        return frmMusteri;
    }

    public void setMusteri(frmMusteriGoruntule frmMusteri) {
        this.frmMusteri = frmMusteri;
    }

    private boolean isTCKNRegistered() throws SQLException {
        boolean flag = true;
        Connection connection = null;
        DbHelper helper = new DbHelper();
        Statement statement = null;
        ResultSet resultSet;
        try {
            connection = helper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("Select * from musteri WHERE TCKN=" + txtTCKN.getText());
            flag = (resultSet.next());

        } catch (SQLException e) {
            helper.showErrorMessage(e);

        } finally {
            statement.close();
            connection.close();
        }

        return flag;
    }

    private boolean isTelNoRegistered() throws SQLException {
        boolean flag = true;
        Connection connection = null;
        DbHelper helper = new DbHelper();
        Statement statement = null;
        ResultSet resultSet;
        if (txtTelNo.getText().isBlank()) {
            flag = false;

        } else {
            try {
                connection = helper.getConnection();
                statement = connection.createStatement();
                resultSet = statement.executeQuery("Select * from musteri WHERE TelNo=" + txtTelNo.getText());
                flag = (resultSet.next());

            } catch (SQLException e) {
                helper.showErrorMessage(e);

            } finally {
                statement.close();
                connection.close();
            }
        }

        return flag;
    }

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        // TODO add your handling code here:
        boolean flag = true;
        Connection connection = null;
        DbHelper helper = new DbHelper();
        PreparedStatement statement = null;

        if (txtTCKN.getText().length() != 11
                || (Integer.valueOf(txtTCKN.getText().charAt(txtTCKN.getText().length() - 1)) - 48) % 2 != 0
                || txtTCKN.getText().charAt(0) == '0'
                || ((((Integer.valueOf(txtTCKN.getText().charAt(0)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(1)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(2)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(3)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(4)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(5)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(6)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(7)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(8)) - 48)
                + (Integer.valueOf(txtTCKN.getText().charAt(9))) - 48) % 10)) - ((Integer.valueOf(txtTCKN.getText().charAt(10))) - 48) != 0
                || (txtTCKN.getText().charAt(0) == txtTCKN.getText().charAt(1)
                && txtTCKN.getText().charAt(1) == txtTCKN.getText().charAt(2)
                && txtTCKN.getText().charAt(2) == txtTCKN.getText().charAt(3)
                && txtTCKN.getText().charAt(3) == txtTCKN.getText().charAt(4)
                && txtTCKN.getText().charAt(4) == txtTCKN.getText().charAt(5)
                && txtTCKN.getText().charAt(5) == txtTCKN.getText().charAt(6)
                && txtTCKN.getText().charAt(6) == txtTCKN.getText().charAt(7)
                && txtTCKN.getText().charAt(7) == txtTCKN.getText().charAt(8)
                && txtTCKN.getText().charAt(8) == txtTCKN.getText().charAt(9)
                && txtTCKN.getText().charAt(10) == '0')) {
            //tckn kısa veya tek sayıyla bitiyorsa veya ilk hanesi 0 ise veya kurallara uymuyorsa
            //tckn hatalı mesajı göster

            JOptionPane.showMessageDialog(null, "TCKN Eksik veya Hatalı", "TCKN Hatalı", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                if (isTCKNRegistered()) {
                    JOptionPane.showMessageDialog(null, "Bu TC Kimlik ile Kayıtlı Kullanıcı Mevcut", "TCKN Zaten Kayıtlı", JOptionPane.INFORMATION_MESSAGE);
                    flag = false;
                } else {
                    if (isTelNoRegistered()) {
                        Object[] options = {"Yine de kaydet", "İptal et"};
                        int n = JOptionPane.showOptionDialog(optCancelContinue,
                                "Bu Telefon Numarası ile kayıtlı bir kullanıcı mevcut.",
                                "Kullanıcı zaten kayıtlı",
                                JOptionPane.YES_NO_OPTION,
                                JOptionPane.QUESTION_MESSAGE,
                                null,
                                options,
                                options[0]);
                        switch (n) {
                            case JOptionPane.YES_OPTION:
                                flag = true;
                                break;
                            case JOptionPane.NO_OPTION:
                                flag = false;
                                break;
                            default:
                                flag = false;
                                break;
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmMusteriEkle.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (flag) {
                try {
                    connection = helper.getConnection();
                    String sql = "insert into musteri(Ad,Soyad,TCKN,TelNo,HESKod,GecmisTurlar,IstenenTurlar,Yorum) values(?,?,?,?,?,?,?,?)";
                    statement = connection.prepareStatement(sql);
                    statement.setString(1, txtAd.getText());
                    statement.setString(2, txtSoyad.getText());
                    statement.setString(3, txtTCKN.getText());
                    statement.setString(4, txtTelNo.getText());
                    statement.setString(5, txtHESKod.getText());
                    statement.setString(6, txtGecmisTurlar.getText());
                    statement.setString(7, txtIstenenTurlar.getText());
                    statement.setString(8, txtYorum.getText());

                    txtAd.setText("");
                    txtSoyad.setText("");
                    txtTCKN.setText("");
                    txtTelNo.setText("");
                    txtHESKod.setText("");
                    txtGecmisTurlar.setText("");
                    txtIstenenTurlar.setText("");
                    txtYorum.setText("");
                    statement.executeUpdate();
                    eklemeBasarili.setLocationRelativeTo(null);
                    eklemeBasarili.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
                    eklemeBasarili.setVisible(true);

                } catch (SQLException e) {
                    helper.showErrorMessage(e);
                } finally {
                    try {
                        statement.close();
                        connection.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(frmMusteriEkle.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                //Action Cancelled
            }
        }
    }//GEN-LAST:event_btnEkleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        eklemeBasarili.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTelNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelNoKeyReleased
        // TODO add your handling code here:
        try {
            Integer.parseInt(txtTelNo.getText());

        } catch (NumberFormatException e) {
            txtTelNo.setText(txtTelNo.getText().replaceAll("[^0-9]", ""));
        }

    }//GEN-LAST:event_txtTelNoKeyReleased

    private void txtTelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelNoActionPerformed

    private void txtTCKNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTCKNKeyReleased
        // TODO add your handling code here:
        try {
            Integer.parseInt(txtTCKN.getText());

        } catch (NumberFormatException e) {
            txtTCKN.setText(txtTCKN.getText().replaceAll("[^0-9]", ""));
        }
    }//GEN-LAST:event_txtTCKNKeyReleased

    private void txtAdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdKeyReleased
        // TODO add your handling code here:
        txtAd.setText(txtAd.getText().replaceAll("^\\s+", ""));
    }//GEN-LAST:event_txtAdKeyReleased

    private void txtSoyadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoyadKeyReleased
        // TODO add your handling code here:
        txtSoyad.setText(txtSoyad.getText().replaceAll("^\\s+", ""));
    }//GEN-LAST:event_txtSoyadKeyReleased

    private void txtGecmisTurlarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGecmisTurlarKeyReleased
        // TODO add your handling code here:
        txtGecmisTurlar.setText(txtGecmisTurlar.getText().replaceAll("^\\s+", ""));
    }//GEN-LAST:event_txtGecmisTurlarKeyReleased

    private void txtHESKodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHESKodKeyReleased
        // TODO add your handling code here:
        txtHESKod.setText(txtHESKod.getText().replaceAll("^\\s+", ""));
    }//GEN-LAST:event_txtHESKodKeyReleased

    private void txtIstenenTurlarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIstenenTurlarKeyReleased
        // TODO add your handling code here:
        txtIstenenTurlar.setText(txtIstenenTurlar.getText().replaceAll("^\\s+", ""));
    }//GEN-LAST:event_txtIstenenTurlarKeyReleased

    private void txtYorumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYorumKeyReleased
        // TODO add your handling code here:
        txtYorum.setText(txtYorum.getText().replaceAll("^\\s+", ""));

    }//GEN-LAST:event_txtYorumKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMusteriEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmMusteriEkle().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JDialog eklemeBasarili;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane optCancelContinue;
    private javax.swing.JOptionPane optPaneUyari;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtGecmisTurlar;
    private javax.swing.JTextField txtHESKod;
    private javax.swing.JTextField txtIstenenTurlar;
    private javax.swing.JTextField txtSoyad;
    private javax.swing.JTextField txtTCKN;
    private javax.swing.JTextField txtTelNo;
    private javax.swing.JTextField txtYorum;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the frmMusteri
     */
    /**
     * @param frmMusteri the frmMusteri to set
     */
}
