/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ustunerturizm2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author iserh
 */
public class frmTurOlustur extends javax.swing.JFrame {

    DefaultListModel model = new DefaultListModel();
    DefaultTableModel dfmodel = new DefaultTableModel();

    /**
     * Creates new form frmTurOlustur
     */
    public frmTurOlustur() {

        initComponents();
        populateTable();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTurAdi = new javax.swing.JTextField();
        txtHareketTarihi = new javax.swing.JTextField();
        txtDonusTarihi = new javax.swing.JTextField();
        txtHareketSaati = new javax.swing.JTextField();
        txtHareketYeri = new javax.swing.JTextField();
        txtTurDanismani = new javax.swing.JTextField();
        txtTurDanismaniTelNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnTurOlustur = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOtobus = new javax.swing.JTable();
        txtOtobusAra = new javax.swing.JTextField();
        btnOtobusSec = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblSeciliOtobus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Tur Adı");

        jLabel2.setText("Hareket Tarihi");

        jLabel3.setText("Dönüş Tarihi");

        jLabel4.setText("Hareket Saati");

        jLabel5.setText("Hareket Yeri");

        jLabel6.setText("Tur Danışmanı");

        jLabel7.setText("Danışman Tel");

        btnTurOlustur.setText("Oluştur");
        btnTurOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurOlusturActionPerformed(evt);
            }
        });

        jLabel8.setText("Otobüs Seçimi");

        tblOtobus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Plaka", "Koltuk Sayısı"
            }
        ));
        jScrollPane1.setViewportView(tblOtobus);

        txtOtobusAra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOtobusAraKeyReleased(evt);
            }
        });

        btnOtobusSec.setText("Otobüs Seç");
        btnOtobusSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtobusSecActionPerformed(evt);
            }
        });

        jLabel9.setText("Plaka-Koltuk Sayısı");

        jLabel10.setText("Seçilen Otobüs");

        lblSeciliOtobus.setText("Otobüs Seçiniz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(btnTurOlustur, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTurAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTurDanismaniTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtHareketTarihi, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                        .addComponent(txtDonusTarihi)
                                        .addComponent(txtHareketSaati)
                                        .addComponent(txtHareketYeri)
                                        .addComponent(txtTurDanismani)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOtobusSec, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtOtobusAra, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSeciliOtobus, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTurAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHareketTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDonusTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHareketSaati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHareketYeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTurDanismani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTurDanismaniTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOtobusAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOtobusSec)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblSeciliOtobus))
                .addGap(11, 11, 11)
                .addComponent(btnTurOlustur)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int turid;
    private void btnTurOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurOlusturActionPerformed
        // TODO add your handling code here:
        Connection connection;
        DbHelper helper = new DbHelper();
        PreparedStatement statement;
        if (otobusSecildi) {
            try {
                connection = helper.getConnection();
                String sql = "insert into turlar(turadi,hareket_tarihi,donus_tarihi,hareket_saati,"
                        + "hareket_yeri,tur_danismani,tur_otobusu_id) values(?,?,?,?,?,?,?)";
                statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
                statement.setString(1, txtTurAdi.getText());
                statement.setString(2, txtHareketTarihi.getText());
                statement.setString(3, txtDonusTarihi.getText());
                statement.setString(4, txtHareketSaati.getText());
                statement.setString(5, txtHareketYeri.getText());
                statement.setString(6, txtTurDanismani.getText() + " " + txtTurDanismaniTelNo.getText());
                statement.setInt(7, otobusid);
                statement.execute();
                ResultSet rs = statement.getGeneratedKeys();
                rs.next();
                turid = (int) rs.getLong(1);
                frmKoltukEkrani frmTurYolcu = new frmKoltukEkrani();
                frmTurYolcu.setTurid(turid);
                frmTurYolcu.createKoltuk();
                frmTurYolcu.setKoltukLayout();
                frmTurYolcu.setVisible(true);

            } catch (SQLException ex) {
                Logger.getLogger(frmOtobusEkle.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println(ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tur Oluşturmak İçin Otobüs Seçmelisiniz.", "Otobüs Seçilmedi", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnTurOlusturActionPerformed

    private void txtOtobusAraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOtobusAraKeyReleased
        // TODO add your handling code here:
        String searchKey = txtOtobusAra.getText();
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<>(dfmodel);
        tblOtobus.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(searchKey));
    }//GEN-LAST:event_txtOtobusAraKeyReleased
    int selectedRow;
    int otobusid = 0;
    boolean otobusSecildi = false;
    private void btnOtobusSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtobusSecActionPerformed
        // TODO add your handling code here:        
        selectedRow = tblOtobus.getSelectedRow();        
        otobusid = (Integer) tblOtobus.getModel().getValueAt(tblOtobus.convertRowIndexToModel(selectedRow), 0);
        lblSeciliOtobus.setText("Plaka: "+tblOtobus.getModel().getValueAt(tblOtobus.convertRowIndexToModel(selectedRow), 1)+" Koltuk sayısı: "+tblOtobus.getModel().getValueAt(tblOtobus.convertRowIndexToModel(selectedRow), 2));
        if (otobusid != 0)
            otobusSecildi = true;
    }//GEN-LAST:event_btnOtobusSecActionPerformed

    public ArrayList<Otobus> getOtobus() throws SQLException {
        Connection connection = null;
        DbHelper helper = new DbHelper();
        Statement statement = null;
        ResultSet resultSet;
        ArrayList<Otobus> otobusler = null;
        try {
            connection = helper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("Select * from otobus");
            otobusler = new ArrayList<>();
            while (resultSet.next()) {
                otobusler.add(new Otobus(resultSet.getInt("ID"),
                        resultSet.getString("plaka"),
                        resultSet.getInt("koltuksayisi")));

            }
        } catch (SQLException e) {
            helper.showErrorMessage(e);

        } finally {
            statement.close();
            connection.close();
        }
        return otobusler;

    }

    public void populateTable() {
        dfmodel.setRowCount(0);
        dfmodel = (DefaultTableModel) tblOtobus.getModel();
        try {
            ArrayList<Otobus> otobusler = getOtobus();
            for (Otobus otobus : otobusler) {
                Object[] row = {
                    otobus.getId(),
                    otobus.getPlaka(),
                    otobus.getKoltukSayisi()};
                dfmodel.addRow(row);

            }
            if (tblOtobus.getColumnName(0).equals("ID")) {
                tblOtobus.removeColumn(tblOtobus.getColumn("ID"));
            }
        } catch (SQLException ex) {
            DbHelper help = new DbHelper();
            help.showErrorMessage(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTurOlustur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmTurOlustur().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtobusSec;
    private javax.swing.JButton btnTurOlustur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSeciliOtobus;
    private javax.swing.JTable tblOtobus;
    private javax.swing.JTextField txtDonusTarihi;
    private javax.swing.JTextField txtHareketSaati;
    private javax.swing.JTextField txtHareketTarihi;
    private javax.swing.JTextField txtHareketYeri;
    private javax.swing.JTextField txtOtobusAra;
    private javax.swing.JTextField txtTurAdi;
    private javax.swing.JTextField txtTurDanismani;
    private javax.swing.JTextField txtTurDanismaniTelNo;
    // End of variables declaration//GEN-END:variables
}
