/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ustunerturizm2;

import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iserh
 */
public class frmTurGoruntule extends javax.swing.JFrame {

    DefaultListModel model = new DefaultListModel();
    DefaultTableModel dfmodel = new DefaultTableModel();

    /**
     * Creates new form frmTurGoruntule
     */
    public frmTurGoruntule() {
        initComponents();
        setLocationRelativeTo(null);
        tblTurlar.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        optCancelContinue = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTurlar = new javax.swing.JTable();
        txtTurAdiylaAra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        brnTurBilgiDuzenle = new javax.swing.JButton();
        btnTurKoltuk = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tblTurlar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tur Adı", "Hareket Tarihi", "Dönüş Tarihi", "Hareket Saati", "Hareket Yeri", "Tur Danışmanı", "turotobusid"
            }
        ));
        tblTurlar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTurlarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTurlar);

        jLabel1.setText("Tur Adıyla Arama");

        brnTurBilgiDuzenle.setText("Tur Koltuk Dizilimi Görüntüle");
        brnTurBilgiDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnTurBilgiDuzenleActionPerformed(evt);
            }
        });

        btnTurKoltuk.setText("Tur Bilgilerini Düzenle");
        btnTurKoltuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurKoltukActionPerformed(evt);
            }
        });

        jButton1.setText("Excel Dökümü Oluştur");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Sil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(brnTurBilgiDuzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTurKoltuk, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTurAdiylaAra)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brnTurBilgiDuzenle)
                    .addComponent(btnTurKoltuk)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(0, 41, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTurAdiylaAra, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int selectedRow;
    private void brnTurBilgiDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnTurBilgiDuzenleActionPerformed
        // TODO add your handling code here:
        frmKoltukEkrani frmTurGor = new frmKoltukEkrani();
        selectedRow = tblTurlar.getSelectedRow();
        int id = (Integer) tblTurlar.getModel().getValueAt(tblTurlar.convertRowIndexToModel(selectedRow), 0);
        frmTurGor.setTurid(id);
        try {
            frmTurGor.getKoltukSayisi();
        } catch (SQLException ex) {
            Logger.getLogger(frmTurGoruntule.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmTurGor.setKoltukLayout();
        frmTurGor.setVisible(true);

    }//GEN-LAST:event_brnTurBilgiDuzenleActionPerformed
    private int turid = 0;

    public ArrayList<Tur> getGoruntulenenTur() throws SQLException {
        int id = (Integer) tblTurlar.getModel().getValueAt(tblTurlar.convertRowIndexToModel(selectedRow), 0);
        Connection connection = null;
        DbHelper helper = new DbHelper();
        Statement statement = null;
        ResultSet resultSet;
        ArrayList<Tur> GoruntulenenTur = null;
        try {
            connection = helper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("Select * from turlar WHERE ID=" + id);
            GoruntulenenTur = new ArrayList<>();
            while (resultSet.next()) {
                GoruntulenenTur.add(new Tur(resultSet.getInt("ID"),
                        resultSet.getString("turadi"),
                        resultSet.getString("hareket_tarihi"),
                        resultSet.getString("donus_tarihi"),
                        resultSet.getString("hareket_saati"),
                        resultSet.getString("hareket_yeri"),
                        resultSet.getString("tur_danismani"),
                        resultSet.getInt("tur_otobusu_id"))
                );

            }
        } catch (SQLException e) {
            helper.showErrorMessage(e);

        } finally {
            statement.close();
            connection.close();
        }
        return GoruntulenenTur;
    }
    private void tblTurlarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTurlarMouseClicked
        // TODO add your handling code here:
        selectedRow = tblTurlar.getSelectedRow();
    }//GEN-LAST:event_tblTurlarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        selectedRow = tblTurlar.getSelectedRow();

        turid = (Integer) tblTurlar.getModel().getValueAt(tblTurlar.convertRowIndexToModel(selectedRow), 0);
        ExcelDokumu dokum = new ExcelDokumu(turid);
        try {
            try {
                try {
                    dokum.ExcelDokumOlustur();
                } catch (URISyntaxException ex) {
                    Logger.getLogger(frmTurGoruntule.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "Masaüstüne Excel Dökümü Oluşturuldu"
                        + "", "İşlem Başarılı", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(frmTurGoruntule.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(frmTurGoruntule.class.getName()).log(Level.SEVERE, null, ex);
        }

        turid = 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int id = (Integer) tblTurlar.getModel().getValueAt(tblTurlar.convertRowIndexToModel(selectedRow), 0);
        Connection connection = null;
        DbHelper helper = new DbHelper();
        PreparedStatement statement = null;
        Object[] options = {"Sil", "İptal et"};
        int n = JOptionPane.showOptionDialog(optCancelContinue,
                "Bu turu silmek istediğinize emin misiniz?",
                "Emin misiniz?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        switch (n) {
            case JOptionPane.YES_OPTION:
                try {
                connection = helper.getConnection();
                String sql = "DELETE from turlar WHERE ID=" + id;
                statement = connection.prepareStatement(sql);
                statement.executeUpdate();
                JOptionPane.showMessageDialog(null, "Tur silindi", "İşlem Başarılı", JOptionPane.INFORMATION_MESSAGE);
                populateTable();

            } catch (SQLException ex) {
                Logger.getLogger(frmMusteriGoruntule.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    statement.close();
                    connection.close();
                } catch (SQLException ex) {
                    Logger.getLogger(frmMusteriEkle.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                break;
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnTurKoltukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurKoltukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTurKoltukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTurGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTurGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTurGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTurGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmTurGoruntule().setVisible(true);
        });
    }

    public ArrayList<Tur> getTur() throws SQLException {
        Connection connection = null;
        DbHelper helper = new DbHelper();
        Statement statement = null;
        ResultSet resultSet;
        ArrayList<Tur> turlar = null;
        try {
            connection = helper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("Select * from turlar");
            turlar = new ArrayList<>();
            while (resultSet.next()) {
                turlar.add(new Tur(resultSet.getInt("ID"),
                        resultSet.getString("turadi"),
                        resultSet.getString("hareket_tarihi"),
                        resultSet.getString("donus_tarihi"),
                        resultSet.getString("hareket_saati"),
                        resultSet.getString("hareket_yeri"),
                        resultSet.getString("tur_danismani"),
                        resultSet.getInt("tur_otobusu_id")));

            }
        } catch (SQLException e) {
            helper.showErrorMessage(e);

        } finally {
            statement.close();
            connection.close();
        }
        return turlar;

    }

    public void populateTable() {
        dfmodel.setRowCount(0);
        dfmodel = (DefaultTableModel) tblTurlar.getModel();
        try {
            ArrayList<Tur> turlar = getTur();
            for (Tur tur : turlar) {
                Object[] row = {
                    tur.getId(),
                    tur.getTuradi(),
                    tur.getHareket_tarihi(),
                    tur.getDonus_tarihi(),
                    tur.getHareket_saati(),
                    tur.getHareket_yeri(),
                    tur.getTur_danismani(),
                    tur.getTur_otobusu_id()
                };
                dfmodel.addRow(row);

            }

        } catch (SQLException ex) {
            DbHelper help = new DbHelper();
            help.showErrorMessage(ex);
        }
        if (tblTurlar.getColumnName(0).equals("ID")) {
            tblTurlar.removeColumn(tblTurlar.getColumn("ID"));
            tblTurlar.removeColumn(tblTurlar.getColumn("turotobusid"));
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnTurBilgiDuzenle;
    private javax.swing.JButton btnTurKoltuk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JOptionPane optCancelContinue;
    private javax.swing.JTable tblTurlar;
    private javax.swing.JTextField txtTurAdiylaAra;
    // End of variables declaration//GEN-END:variables
}
